# {{SERVICE_NAME}}

This repository was generated by Harness HQ for the service id `{{SERVICE_ID}}`.

## Current defaults

- Provider: `{{PROVIDER}}`
- Runtime policy: Codex-first
- Default Node runtime target: {{DEFAULT_NODE_LABEL}}
- Default web stack target: {{DEFAULT_WEB_STACK}}
- Default deploy target: {{DEPLOY_PREFERENCE}}
- Default domain preference: {{DOMAIN_PREFERENCE}}

## First steps

1. Initialize git if needed.
2. Switch Codex to this generated repo and keep the product conversation here instead of HQ.
3. Use `{{DEFAULT_NODE_VERSION}}` before running npm commands. The repo includes `.nvmrc` and `.node-version`.
4. Set the local git hooks path with `git config core.hooksPath .githooks`.
5. Create a branch such as `task/{{BOOTSTRAP_TASK_ID}}-init`.
6. Read `docs/design/art-direction.kr.md`, `docs/design/ui-principles.kr.md`, and `docs/design/browser-review.kr.md`.
7. Run `python3 scripts/harness.py pre-task`.
8. Start the first implementation slice described in `docs/exec-plans/active/{{BOOTSTRAP_TASK_ID}}.kr.md`.
9. For UI or flow work, review the running app in a browser before treating the result as complete.

## Required artifacts

- Task plan before editing
- Art direction and UI principles before polished UI work
- Browser review evidence before polished UI or flow sign-off
- Run report before completion
- Evidence bundle for flows that are verified
- Journal, architecture reasoning, and harness feedback updates that match the task

## Python requirement

The harness scripts use PyYAML. Install it with `python3 -m pip install pyyaml` when the environment does not already provide it.

## App runtime baseline

- Node runtime: `{{DEFAULT_NODE_LABEL}}`
- Next.js line: `{{DEFAULT_NEXT_LINE}}`
- React line: `{{DEFAULT_REACT_LINE}}`
