# {{SERVICE_NAME}}

This repository was generated by Harness HQ for the service id `{{SERVICE_ID}}`.

## Current defaults

- Provider: `{{PROVIDER}}`
- Runtime policy: Codex-first
- Default web stack target: Next.js + TypeScript
- Default deploy target: {{DEPLOY_PREFERENCE}}
- Default domain preference: {{DOMAIN_PREFERENCE}}

## First steps

1. Initialize git if needed.
2. Set the local git hooks path with `git config core.hooksPath .githooks`.
3. Create a branch such as `task/{{BOOTSTRAP_TASK_ID}}-init`.
4. Run `python3 scripts/harness.py pre-task`.
5. Start the first implementation slice described in `docs/exec-plans/active/{{BOOTSTRAP_TASK_ID}}.kr.md`.

## Required artifacts

- Task plan before editing
- Run report before completion
- Evidence bundle for flows that are verified
- Journal, architecture reasoning, and harness feedback updates that match the task

## Python requirement

The harness scripts use PyYAML. Install it with `python3 -m pip install pyyaml` when the environment does not already provide it.
